const USERS_CODES = {
  NAME_BUSY: 'NAME_IS_OCCUPIED',
  USER_NOT_EXIST: 'USER_NOT_EXIST'
}

const HTTP_CODES = {
  OK: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  INTERNAL_SERVER_ERROR: 500
}

export {USERS_CODES, HTTP_CODES}